# Generated by Django 5.0.2 on 2024-02-23 13:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(choices=[('Bond Asset Swap', 'Bond Asset Swap'), ('Bond Outright', 'Bond Outright'), ('Bond Butterfly', 'Bond Butterfly'), ('Bond Switch', 'Bond Switch'), ('Irs Outright', 'Irs Outright'), ('Irs Curve', 'Irs Curve'), ('Irs Butterfly', 'Irs Butterfly'), ('Invoices Spread', 'Invoices Spread'), ('Generic Enquiry', 'Generic Enquiry'), ('Swap Butterfly', 'Swap Butterfly'), ('Swap Curve', 'Swap Curve'), ('Swap List', 'Swap List'), ('Swap Outright', 'Swap Outright')], max_length=30)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=15)),
                ('status_comments', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(1000000)])),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trades.bank')),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trades.trader')),
            ],
        ),
    ]
