name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version:
          - "3.12"

    name: Test
    runs-on: ${{ matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version : ${{ matrix.python-version }}

      - name: Install PostgreSQL (macOS)
        run: |
          brew install postgresql

      - name: Install dependencies
        run: |
          pip install django
          pip install dj-database-url  
          pip install -r requirements.txt
          pip install psycopg2-binary   
          python -m pip install pytest .

      - name: Set DJANGO_SETTINGS_MODULE
        run: echo "DJANGO_SETTINGS_MODULE=TMSystem.settings" >> $GITHUB_ENV

      - name: Run tests
        run: pytest